common: switch exclude-packages to a postprocess
In a build-via-container workflow we don't have support for the
`exclude-packages:` treefile directive. See also

https://github.com/coreos/fedora-coreos-config/commit/4f921e020552cc595d4f688785949bcc2b794449

diff --git a/common.yaml b/common.yaml
--- a/common.yaml
+++ b/common.yaml
@@ -212,6 +212,38 @@ postprocess:
     # Nuke broken alternatives links
     rm -f /etc/alternatives/*-man
 
+  # Implement exclude-packages: in a postprocess because when building
+  # via container we don't have exclude-packages functionality.
+  #
+  # These are things we don't expect to ship on the host and want to catch
+  # if they ever sneak in.
+  #
+  # Copied from https://github.com/coreos/fedora-coreos-config/blob/c0abc9cd871327349951ab59994d83466e2740fe/manifests/fedora-coreos.yaml#L201-L237
+  - |
+    #!/usr/bin/env bash
+    set -x
+    # Don't fail on s390x for now as Perl gets installed via s390utils-core
+    # See: https://github.com/coreos/fedora-coreos-tracker/issues/1217
+    excludes=(
+      # https://github.com/coreos/rpm-ostree/pull/1789/files/a0cd999a8acd5b40ec1024a794a642916fbc8ff8#diff-fc2076dc46933204a7a798f544ce3734
+      # People need to use `rpm-ostree kargs` instead.
+      grubby
+      # udisks2 is a fwupd recommends only need for encrypted swap checks
+      udisks2
+      # dhcp-client is recommended by chrony for handling NTP servers given out via
+      # DHCP, but we have a NM dispatcher script that is doing that
+      # See: https://bugzilla.redhat.com/show_bug.cgi?id=1930468
+      # See: https://bugzilla.redhat.com/show_bug.cgi?id=1800901
+      dhcp-client
+    )
+    # Determine if anything that isn't allowed is actually provided.
+    actuals="$(rpm -q --whatprovides ${excludes[@]} | grep -v 'no package provides')"
+    if [ ! -z "${actuals}" ]; then
+        echo "Something is providing excluded RPM functionality!" 1>&2
+        echo "${actuals}" 1>&2
+        exit 1
+    fi
+
 # Add the sudo group to /etc/group
 # This is re-implemented below for the container-native flow. Nuke this once
 # that's the only path we support.
